### ISSUE TITLE
RPC function for message detail view not displaying full data with v1.2.9 upgrade

### ISSUE THREAD

**Issue by gordoncolyn** [mailwatch/1.2.0#1073]
I upgraded from v1.2.6 to v1.2.9 and have found that the view message page does not display all the email data.  It only shows Received on, Received by and Received from details.  All the rest of the message detail from Received via does not show.

When I change my httpd.conf file and point back to the 1.26 data all the info displays.

I have 3 mail servers, 1 mysql server and an http server for clients to login and view quarantined email and reports.  On v1.2.6 everything works fine.  v1.2.9 has the bug.

### Version and method
 - MailWatch Version: [ stable 1.2.9 ]
 - Install type: [ Zip install ]
 - Updated from an older MailWatch or fresh install: [ Upgrade ] (from 1.2.6 to 1.2.9)

### Server configuration
 - Operation System: [ CentOS version 6.9 ]
 - PHP version: [ 5.3  ]
 - Database: [ MySQL version 5.7.22 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache version 2.2 ]

### Client configuration 
 - Operation System: [ windows 10 ] 
 - Browser: [ firefox]

**Comment by Skywalker-11** [comment]
Are there any errors in the logs of the webservers?

**Comment by gordoncolyn** [comment]
No Errors, this is all I see in access log;
xxx.xxx.xxx.xxx - - [02/Jun/2018:09:25:16 +0200] "POST /mailscanner/rpcserver.php
HTTP/1.0" 200 145 "-" "XML-RPC for PHP 3.0.0.beta"

**Comment by Skywalker-11** [comment]
Are the details shown correctly on the view message page wg https://x.x.x.x/detail.php (opened when clicking the info sign in the recent messages/qurantine list?

Or does it only happen for the /viewmail.php?

Can you post a screenshot showing the differences?

**Comment by davidgknox** [comment]
Just finished upgrading to 1.2.9 and expierencing the same issue since the upgrade. Only "Received on", "Received by" and "Received from" are displayed, all other header info is missing when viewing it through the "Recent Massages" or the "Quarantine" list.

**Comment by gordoncolyn** [comment]
I get the same result on the detail page;
![image](https://user-images.githubusercontent.com/31371167/40878667-7a22cb3a-6694-11e8-84dd-a7eb58fcd42f.png)

**Comment by gordoncolyn** [comment]
It should be;
![image](https://user-images.githubusercontent.com/31371167/40878682-ac7b6312-6694-11e8-9c53-17670d7de8f7.png)

**Comment by Skywalker-11** [comment]
Couldn't reproduce it for current debian 9/postfix/apache 2.4/MariaDB 10.1/MW 1.2.9/PHP 7.0.27/MS 5.0.7-2 with/without RPC

detail.php shows the expected fields including header meta-data.

![image](https://user-images.githubusercontent.com/11180862/40881080-3b746f4a-66be-11e8-86d1-102a5fa0baa4.png)

@davidgknox which system configuration (OS, MTA, MS version) are you using. Do you also use RPC? Which version was the last one working?

@gordoncolyn @davidgknox are you using the same config files for both configurations or are there different ones / did you adjust the paths in the config to match the newer version? Have you run upgrade.php after switching to the new version? Have you also updated the remote servers? Any logs in the apache/mail log files on the webui or remote servers? Which user type are you using to access the page? I assume you are running the stable release and not the 1.2 branch (dev)?

Also keep in mind that the detail.php and viewmail.php show different contents as the viewmail.php is supposed for non technical users who probabyl don't understand headers and stuff and so the information there is kept to a minimum which is also visible in normal mail clients. For this issue I understood it the way that the problem is with the detail.php. Please correct me if you expect the headers on the viewmail.php page.

**Comment by davidgknox** [comment]
Centos 6, Postfix, MS 5.0.7, no RPC.
Works with MW 1.2.8 using the same conf.php file.
Yes, upgrade.php was run.
Neither detail.php or viewmail.php show any data in 1.2.9 when using the Administrator or Domain Administrator accounts.

**Comment by Skywalker-11** [comment]
I think I found a possible problem:
We updated the GeoIP package for 1.2.9 because the legacy GeoIP was discontinued for free use (https://github.com/mailwatch/MailWatch/issues/1037) . 

The GeoLite2 DB seems to requires PHP >= 5.4 (https://github.com/maxmind/GeoIP2-php/blob/master/composer.json#L18)

I have to test it but I guess this causes it to stop after the "Received from" because that is when it would use the GeoIP. 

You can try to comment out the call to use geoip https://github.com/mailwatch/MailWatch/blob/fc680d159a3079ba78a510e36c23280cc8334772/mailscanner/detail.php#L177-L178

**Comment by gordoncolyn** [comment]
Hi,

That is definately the cause.  I commented out the code and get the full data returned.  i will create a process to upgrade to a later version of php tonite and confirm.

Thanks

**Comment by gordoncolyn** [comment]
Hi,

I upgraded php5.3 to php5.6 and everything is working 100%
