### ISSUE TITLE
can't see outgoing mails in Mailwatch

### ISSUE THREAD

**Issue by funtomko** [mailwatch/1.2.0#1077]
Hi all!

I'm just new and need your advice. We have installed MailWatch v1.2.0 - Beta 8 with Mailscanner. We are using predefined user rights (user, domain administrator, administrator). We have problem that domain administrator doesn't see outgoing emails in Mailwatch but he is able to see all incoming emails of his domain. Is this some bug or some problem in our configuration? I'm not the person who did the installation and configuration but I'm trying to adminstrate it now.

Thank you,
Tomas

**Comment by Skywalker-11** [comment]
Please try the latest release https://github.com/mailwatch/MailWatch/releases/tag/v1.2.9
There were some changes and fixes since beta 8 that may solve your problem

If that doesn't help please describe the problem according to https://github.com/mailwatch/MailWatch/blob/1.2/.github/ISSUE_TEMPLATE.md including your system setup

**Comment by Skywalker-11** [comment]
@funtomko any news on this?

**Comment by funtomko** [comment]
Hi Skywalker,

thak you for feedback. We have another server where is installed MailWatch Version: 1.2.8, Operating System Version: CentOS Linux 7 (Core), Postfix Version: 2.10.1,PHP Version: 5.4.16, MySQL Version: 5.5.56-MariaDB.
This server is used for receiving emails of some domains and the older server (with  MailWatch v1.2.0 - Beta 8, Centos, PHP Version = 5.4.16,MySQL Version = 5.5.56-MariaDB) is used for sending emails (on exchange server there is send connector to this server). 
For now I did only test from newer server via telnet as sender xxx@mydomain.com and if I set "domain admin" rights I couldn't see this test email. I can see incoming emails to @mydomain.com with "domain admin" rights. Maybe this test via telnet is not same like from exchange but in can see this telnet email in Mailwatch with "Administartor" rights.

Br,
Tomas

**Comment by Skywalker-11** [comment]
Did you run upgrade.php (even after fresh install)?
Do you have `ALLOW_NO_USER_DOMAIN` set in the conf.php.
Also keep in mind that since 1.2.6 domain admins are only able to see mails for their own domain (same mail domain).

Also was your test mail scanned by MailScanner (look in your mail.log)? Depending on how you send the test mail this would not go through postfix (and as such not through MailScanner) but instead sends it directly to the target host.

**Comment by funtomko** [comment]
Hi @Skywalker-11 ,

I don't know if upgrade.php was applied. I didn't find this in documentation from installtion.

I checked mail.log and it seems that email went throuh the postfix.

 postfix/cleanup[194821]: 1C09A111DA828: hold: header Received: from domain.com (localhost [127.0.0.1])??by mailserver.com (Postfix) with SMTP id 1C09A111DA828??for...

Also in MW i can see
Message Headers: | Received: from domain.com (localhost [127.0.0.1])     by mailserver.com (Postfix) with SMTP id 1C09A111DA828

Then I checked conf.php. but there is //
//define('ALLOW_NO_USER_DOMAIN',true);

Should I remove // ? Is theen needed reboot of MW server?

Thank you for your help
Tomas

**Comment by Skywalker-11** [comment]
> Then I checked conf.php. but there is //
> //define('ALLOW_NO_USER_DOMAIN',true);

Its the default and should work

Assuming the domain admin account with username `dm@example.com`, the sender for a test mail is `user@otherexample.com` and the receiver is `someuser@example.com`:
A very basic test should look something like this (lines prefixed with `#` is your input others is servers response):
``` smtp
# telnet 127.0.0.1 25
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
220 somehostname ESMTP Postfix
# ehlo somehostname
250-PIPELINING
250-SIZE 56800000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
# mail from: user@otherexample.com
250 2.1.0 Ok
# rcpt to: someuser@example.com
250 2.1.5 Ok
# data
354 End data with <CR><LF>.<CR><LF>
# test
# .
250 2.0.0 Ok: queued as E777B78020B
# quit
```

After that the mail should be displayed on the recent message page and message listing when logged in as `dm@example.com`

If that is not the case please run the following mysql query and validate that the to_domain field actually contains the correct receiver domain `example.com`  (replace `<mail_id>` with the actual message id as shown in with the admin account):
`SELECT from_address, from_domain, to_address, to_domain, id FROM maillog where id like "<mail_id>";`

If that basic test works also make sure that you do not experience the MailScanner issue https://github.com/MailScanner/v5/issues/109 (fixed in MailScanner v5.0.7-1 and above)

**Comment by funtomko** [comment]
Hi,

My test from telnet was very similar. But from your test you are testing If you can see received email. 
(domain admin - dm@example.com, rcpt to: someuser@example.com) That works fine for domain admin.

Problem is if sender is from domain like domain admin (dm@example.com)
mail from: someuser@example.com
rcpt to: user@otherexample.com

When I login with dm@example.com I can't see email from someuser@example.com. (I can see this email only with administrator rights)

MailScanner-5.0.7-2.

Br,
Tomas

**Comment by Skywalker-11** [comment]
@funtomko Sorry you are correct. My mistake on copy/paste but I tested your test case 😄 (and its working here)

Did you try the mysql command? Of course for your case its the from_domain field which should contain the sender domain example.com

**Comment by stefaweb** [comment]
Hi @funtomko!

If you want test your servers as using "telnet" , look at this binary: `swaks`

**Comment by Skywalker-11** [comment]
@funtomko Did you try the mysql command? Of course for your case its the from_domain field which should contain the sender domain example.com

**Comment by funtomko** [comment]
Hi, sorry for later respond. I haven't tried it. I'm not sure how to use the command, could you instruct me step by step please? 
Tomas

**Comment by Skywalker-11** [comment]
Run the following command:
`mysql -u DB_USER -p DB_NAME -e 'SELECT from_address, from_domain, to_address, to_domain, id FROM maillog where id like "MAILID"'`

Replace `MAILID` with the mail id as shown for a on the gui and `DB_USER` and `DB_NAME` with the corresponding values from your conf.php. You will be asked for the password (DB_PASS from conf.php)

![untitled](https://user-images.githubusercontent.com/11180862/42410406-79755912-81e9-11e8-8931-39fd2dfd7f93.png)

**Comment by Skywalker-11** [comment]
Can you try v1.2.10. It may fixes your problem
