### ISSUE TITLE
Clicking on incoming or outgoing Mail queue info ( Postfix ) ends current user session

### ISSUE THREAD

**Issue by ioncebotari** [mailwatch/1.2.0#1098]
### Issue summary
On a new installation of MailWatch, clicking on "Incoming" or "Outgoing" mail queues abruptly ends the user session. I get a 302 redirect to Location: logout.php?error=timeout , with no errors inside error_log.

### Steps to reproduce
1. Log in to MailWatch
2. Click on "Incoming" or "Outgoing"
3. Receive logout

### Expected result
I should be able to see the actual Postfix queue. And the interesting thing is that it worked fine while the line in conf.php that points to functions.php was wrong

### Actual result
Your session timed out.

### Version and method
 - MailWatch Version: stable 1.2.10
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install:  Fresh install

### Server configuration
 - Operation System:Ubuntu 16.04
 - PHP version:  5.6
 - Database: MySQL Ver 14.14 Distrib 5.7.23
 - Mail Server: Postfix 3.1.0
 - Used web server: [ Apache | Nginx ] version [ version ]

### Client configuration 
 - Operation System: Ubuntu 18.04
 - Browser: Firefox Quantum 61.01

**Comment by Skywalker-11** [comment]
Can you try to clear your browser cache and try again?

Also be aware that since v1.2.3 there is an automatic session timeout after 10 minutes of inactivity. See `define('SESSION_TIMEOUT', 600);` in conf.php to change that time.
Also you can stay on the status page and keep seeing the mail log but as soon as you switch to an other page and the session was timed out you will be redirected to the login page

**Comment by ioncebotari** [comment]
Thank you. After clearing the cache and the cookies everything works fine
