### ISSUE TITLE
If a user was auto created with IMAP, their password is displayed on the interface instead of their full name

### ISSUE THREAD

**Issue by xpufx** [mailwatch/1.2.0#1118]
### Issue summary
Write a short summary of the issue, trying to pinpoint it as much as possible.
Mention the URL where this bug occurs, if applicable.
Please include *full error messages* and *screenshots* if possible.

### Steps to reproduce
1. Make the initial log in with imap with auto create user enabled
2. In the top left username/time box, your password will be displayed instead of your name
3. 

### Expected result
Name should display
### Actual result
password is displayed

### Version and method
 - MailWatch Version: [ stable 1.2.11]

**Comment by xpufx** [comment]
It's not a display issue. It's displaying whatever is in the database for the fullname field. Initial creation has the wrong value inserted in: functions.php -> imap_authenticate ()

```
 "REPLACE INTO users (username, fullname, type, password) VALUES (%s, %s,'U',NULL)",
           quote_smart($username),
          quote_smart($password)
```

The second %s is the fullname field but $password is being inserted.

**Comment by xpufx** [comment]
The real issue is the passwords in the clear in the database of course.

**Comment by xpufx** [comment]
By the way, there's no fullname to insert there since that information is not available via imap auth so both fields should probably just be $username, with perhaps something like (imap) next to it.

**Comment by asuweb** [comment]
Issue confirmed, latent bug unintentionally storing clear text password in database - no requirement to store IMAP Authenticated user's passwords at all. 

Suggest all admins who use IMAP Auth functions to patch code and manually clean database.

Fixed in PR #1119

**Comment by asuweb** [comment]
> The real issue is the passwords in the clear in the database of course.

**Comment by endelwar** [comment]
Thanks @oktayaa for the issue and big thanks to @asuweb for the quick fix!

I've just released version 1.2.12 containing this fix.

**Comment by Skywalker-11** [comment]
@endelwar should there also be a patch in the update that removes the password already stored in plaintext and or mention that in the release notes?

**Comment by endelwar** [comment]
Yes, I think that the upgrade.php should contain this database fix:
```
if (defined('IMAP_AUTOCREATE_VALID_USER') && IMAP_AUTOCREATE_VALID_USER === true) { 
$sql = "UPDATE `users` SET `password` = `username`";
dbquery($sql);
}
```

**Comment by asuweb** [comment]
@endelwar @Skywalker-11 

I thought about this, but there are 2 issues with this:

1. The use of  `IMAP_AUTOCREATE_VALID_USER` doesn't prevent users also being added manually, so the above proposed change to upgrade.php will effectively prevent access to manually added users - but see point 2 below...

2. The issue was that `fullname` in the DB was being populated with a clear text password (this was also visible in the GUI in `User Management`).  Password for IMAP users should only ever be `NULL` as there's no requirement to store the IMAP user's password

A fix from a security point of view would be:

```
if (defined('IMAP_AUTOCREATE_VALID_USER') && IMAP_AUTOCREATE_VALID_USER === true) { 
$sql = "UPDATE `users` SET `fullname` = `username`";
dbquery($sql);
}
```

This would be a non breaking change, and would remove the clear text passwords, the only point of note would be if non-imap users had been created, it would overwrite the `Name` field for those users.

**Comment by endelwar** [comment]
This query should be more specific to this security issue, what do you think?

```sql
UPDATE `users` SET `fullname` = `username` WHERE `type`='U' AND `password` IS NULL
```

**Comment by asuweb** [comment]
Yes, that should work I think.

**Comment by endelwar** [comment]
I'm going to add this to upgrade.php, and then add this query on the release notes on github and website
