### ISSUE TITLE
MailWatch: SQLBlackWhiteList:: Unable to initialise database connection

### ISSUE THREAD

**Issue by janarzz** [mailwatch/1.2.0#1273]
Hi,
i install Mailscanner and Mailwatch, but for now i get error:
MailWatch: SQLBlackWhiteList:: Unable to initialise database connection
I use latest version of Mailwatch and Mailscanner.
OS: Ubuntu server 22.04
postfix+postfixadmin+dovecot

**Comment by Lumanet2012** [comment]
Did you check if all cpan packages are installed ?? 

cpan -i Filesys::Df
cpan -i Sys::SigAction
cpan -i OLE::Storage_Lite
cpan -i DBD::SQLite
cpan -i Encoding::FixLatin
cpan -i Digest::SHA
cpan -i DBD::mysql::st

Those I had to all install in order to get my postfix with mailwatch going. I hope that helps
