### ISSUE TITLE
Review and correct all documentation

### ISSUE THREAD

**Issue by endelwar** [mailwatch/1.2.0#22]
Documentation is out of date, so it should be verified and corrected when necessary
##

**Comment by endelwar** [comment]
A new [branch](https://github.com/mailwatch/1.2.0/tree/gh-pages) has been created to contain MailWatch documentation which can be reached at http://docs.mailwatch.org/

**Comment by endelwar** [comment]
A [new website](http://mailwatch.org/) presenting MailWatch has been created

**Comment by Johanhen** [comment]
Nice site.!

It would be nice to see the gui of mailwatch itself being upgraded to 
some more modern look.
Thank you all for the work on mailwatch, I still use it every day and it 
never has let me down.


regards







Op 11-02-15 om 12:34 schreef Manuel Dalla Lana:

**Comment by endelwar** [comment]
I want to stabilize the 1.2.0 release ASAP and the move to a refactoring of source code and user interface

**Comment by atftb** [comment]
Very nice.

I note on the installing page that it’s developed on Debian and Ubuntu 12.04.  We mostly use Debian here so that’s pretty sweet, but I’m wondering about MailScanner – do you just install that from source?  IIRC Julian usually developed on CentOS and updated packages for the Debian users were pretty much lacking unless one rolled their own.

I’m trying to figure out the best way to keep things up to date with the least amount of effort/confusion.

Thanks…

...Kevin
--
Kevin Miller
Network/email Administrator, CBJ MIS Dept.
155 South Seward Street
Juneau, Alaska 99801
Phone: (907) 586-0242, Fax: (907) 586-4500
Registered Linux User No: 307357

**Comment by endelwar** [comment]
I usually install MailScanner from source; there used to be a debian package maintained by baruwa but last version is 4.84.5-4~wheezy on apt.baruwa.org

**Comment by endelwar** [comment]
good news for debian users: @jcbenton worked really hard and has packaged the new release of MailScanner (4.85.2-2) in .deb format!

**Comment by Skywalker-11** [comment]
Optional steps for Postfix: sql file does not exist anymore

**Comment by Skywalker-11** [comment]
The docs also missing that the webserver must have write access to mailscanner/temp directory

**Comment by stefaweb** [comment]
May be the best is to use mtagroup in /etc/group:

mtagroup:x:1001:clamav,Debian-exim,mail,www-data

**Comment by asuweb** [comment]
All the docs need an overhaul / review (as per this thread).  

@endelwar - Is there any current way to contribute directly to documentation?

**Comment by endelwar** [comment]
There is a separate repository that contains code for docs.mailwatch.org: https://github.com/mailwatch/mailwatch-docs

PR can be sent there and are very very welcome!

**Comment by asuweb** [comment]
Excellent. Thanks

**Comment by endelwar** [comment]
@remkolodder remember the OpenLDAP documentation (see #549)

**Comment by endelwar** [comment]
This issue was moved to mailwatch/mailwatch-docs#21
