### ISSUE TITLE
Filters for deleted users present in database

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#625]
When a user is deleted, the filters are still in the database.  Creating the user again has the old filters.

**Comment by asuweb** [comment]
Thanks - at the moment it seems we don't remove the filters on user deletion - which is a bit of an oversight.  

It shall be fixed

**Comment by stefaweb** [comment]
Great find!

I've found tens of old/unused entries in user_filters on my prod server.

**Comment by asuweb** [comment]
Fixed in PR #626

**Comment by asuweb** [comment]
Perhaps we need to incorporate a cleanup for this in upgrade.php to remove any filters which don't have a corresponding user?

**Comment by stefaweb** [comment]
Could you verify as when we change user / user domain / user admin, all is fine with filters?

Example, if we change `user_old_name` to `user_new_name`.

**Comment by asuweb** [comment]
It doesn't currently work like that.  I'm assuming when it was written that scenario wasn't considered.

It wouldn't be an issue if the db structure used ID's and joins, but that will be too big of a rewrite just now.  

I'll modify the current logic so that if a username is changed it also checks the filters

**Comment by asuweb** [comment]
Fixed in latest commit

**Comment by asuweb** [comment]
This can be closed
